apiVersion: services.tanzu.vmware.com/v1
kind: ServiceBinding
metadata:
    name: music-e73be8
spec:
  alias: music
  serviceRef:
    apiGroup: bitnami.database.tanzu.vmware.com
    kind: PostgreSQLInstance
    name: music
  targetRef:
    apiGroup: apps.tanzu.vmware.com
    kind: ContainerApp
    name: tanzu-music
